-- Oracle
SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL <=24;

-- MySQL
SET @Hour := -1;
SELECT (@Hour := @Hour+1) HOUR, 
(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME)=@Hour) COUNT
FROM ANIMAL_OUTS
WHERE @Hour<23
