-- Oracle
SELECT HOUR(DATETIME), COUNT(DATETIME) FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR(DATETIME)>9 AND HOUR(DATETIME)<20

-- MySQL
SELECT HOUR(DATETIME), COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS
WHERE HOUR(DATETIME)>9 AND HOUR(DATETIME)<19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)
