-- MySQL
SELECT OUTS.ANIMAL_ID, OUTS.NAME FROM ANIMAL_OUTS OUTS JOIN ANIMAL_INS INS USING(ANIMAL_ID)
ORDER BY OUTS.DATETIME-INS.DATETIME DESC LIMIT 2

-- Oracle
SELECT ANIMAL_ID, NAME
    FROM (SELECT INS.ANIMAL_ID, INS.NAME
        FROM ANIMAL_INS INS, ANIMAL_OUTS OUTS
        WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID 
        ORDER BY OUTS.DATETIME - INS.DATETIME DESC)
    WHERE ROWNUM <= 2
